package com.miracl.trust.crypto

import androidx.annotation.Keep

@Keep
internal data class Pass1Proof(val X: ByteArray, val SEC: ByteArray, val U: ByteArray) {
    companion object {
        private const val AUTOGENERATED_MULTIPLIER = 31
    }

    constructor() : this(byteArrayOf(), byteArrayOf(), byteArrayOf())

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Pass1Proof

        if (!X.contentEquals(other.X)) return false
        if (!SEC.contentEquals(other.SEC)) return false
        if (!U.contentEquals(other.U)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = X.contentHashCode()
        result = AUTOGENERATED_MULTIPLIER * result + SEC.contentHashCode()
        result = AUTOGENERATED_MULTIPLIER * result + U.contentHashCode()
        return result
    }
}
