package com.miracl.trust.crypto

import androidx.annotation.Keep

@Keep
data class SigningKeyPair(
    val publicKey: ByteArray,
    val privateKey: ByteArray
) {
    companion object {
        private const val AUTOGENERATED_MULTIPLIER = 31
    }

    constructor() : this(byteArrayOf(), byteArrayOf())

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SigningKeyPair

        if (!publicKey.contentEquals(other.publicKey)) return false
        if (!privateKey.contentEquals(other.privateKey)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = publicKey.contentHashCode()
        result = AUTOGENERATED_MULTIPLIER * result + privateKey.contentHashCode()
        return result
    }


}