package com.miracl.trust.crypto

import androidx.annotation.Keep

@Keep
data class SigningResult(
    val u: ByteArray,
    val v: ByteArray
) {
    companion object {
        private const val AUTOGENERATED_MULTIPLIER = 31
    }

    constructor() : this(byteArrayOf(), byteArrayOf())

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SigningResult

        if (!u.contentEquals(other.u)) return false
        if (!v.contentEquals(other.v)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = u.contentHashCode()
        result = AUTOGENERATED_MULTIPLIER * result + v.contentHashCode()
        return result
    }
}