package com.miracl.trust.model

import androidx.annotation.Keep

/**
 * Object representing the user in the platform.
 * @param identity Identity used for the authentication.
 * @param publicKey Public part of the signing key.
 */
@Keep
data class SigningUser(
    val identity: Identity,
    val publicKey: ByteArray
) {
    companion object {
        private const val AUTOGENERATED_MULTIPLIER = 31
    }

    // AUTOGENERATED
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SigningUser

        if (identity != other.identity) return false
        if (!publicKey.contentEquals(other.publicKey)) return false

        return true
    }

    // AUTOGENERATED
    override fun hashCode(): Int {
        var result = identity.hashCode()
        result = 31 * result + publicKey.contentHashCode()
        return result
    }
}
