package com.miracl.trust.authentication

import androidx.annotation.Keep
import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

@Keep
internal data class Pass1RequestBody(
    @Expose @SerializedName("mpin_id") val mpinId: String,
    @Expose @SerializedName("U") val U: String,
    @Expose @SerializedName("dtas") val dtas: String,
    @Expose @SerializedName("scope") val scope: Array<String>,
    @Expose @SerializedName("publicKey") val publicKey: String?
) {
    companion object {
        private const val AUTOGENERATED_MULTIPLIER = 31
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Pass1RequestBody

        if (mpinId != other.mpinId) return false
        if (U != other.U) return false
        if (dtas != other.dtas) return false
        if (!scope.contentEquals(other.scope)) return false
        if (publicKey != other.publicKey) return false

        return true
    }

    override fun hashCode(): Int {
        var result = mpinId.hashCode()
        result = AUTOGENERATED_MULTIPLIER * result + U.hashCode()
        result = AUTOGENERATED_MULTIPLIER * result + dtas.hashCode()
        result = AUTOGENERATED_MULTIPLIER * result + scope.contentHashCode()
        result = AUTOGENERATED_MULTIPLIER * result + (publicKey?.hashCode() ?: 0)
        return result
    }
}
